### ISSUE TITLE
이게 뭐죠

### ISSUE THREAD

**Issue by X-Cube-Inc** [FlagFan34272/NESTJS_Learning#1]
그냥 이게 뭐죠

**Comment by FlagFan34272** [comment]
> 그냥 이게 뭐죠

누구신가요

**Comment by X-Cube-Inc** [comment]
과거에 디코로 같이 얘기하신적이 있던것만 알려드릴게요.

**Comment by X-Cube-Inc** [comment]
그래서 어떤 프로젝트인지 설명해주실수 있나요?

**Comment by FlagFan34272** [comment]
> 과거에 디코로 같이 얘기하신적이 있던것만 알려드릴게요.

누구냐고요

**Comment by FlagFan34272** [comment]
> 그래서 어떤 프로젝트인지 설명해주실수 있나요?

생각할수록 어이없는게 있어서 그러는데 누군지부터 말하세요
